name: Deploy

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les push vers la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise la dernière version d'Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Récupère le code source du dépôt

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Configure Node.js version 14

      - name: Install dependencies
        run: npm install  # Installe les dépendances du projet

      - name: Build
        run: npm run build  # Exécute la commande de construction, si applicable

      - name: Deploy
        run: echo "Deploy step"  # Remplacez ceci par votre propre commande de déploiement, si nécessaire
